name: testing-workshop

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
      - name: Install dependencies and test
        run: npm ci
          npm test
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: output/test/code.coverage.html